#include "hitsimple/lexer/Token.h"

namespace hitsimple::lexer {

std::string_view tokenKindName(TokenKind kind) {
  switch (kind) {
  case TokenKind::End:
    return "End";
  case TokenKind::Invalid:
    return "Invalid";
  case TokenKind::Newline:
    return "Newline";
  case TokenKind::Identifier:
    return "Identifier";
  case TokenKind::Integer:
    return "Integer";
  case TokenKind::Float:
    return "Float";
  case TokenKind::Char:
    return "Char";
  case TokenKind::String:
    return "String";
  case TokenKind::KeywordFunc:
    return "KeywordFunc";
  case TokenKind::KeywordNew:
    return "KeywordNew";
  case TokenKind::KeywordStatic:
    return "KeywordStatic";
  case TokenKind::KeywordExtern:
    return "KeywordExtern";
  case TokenKind::KeywordReturn:
    return "KeywordReturn";
  case TokenKind::KeywordIf:
    return "KeywordIf";
  case TokenKind::KeywordElse:
    return "KeywordElse";
  case TokenKind::KeywordFor:
    return "KeywordFor";
  case TokenKind::KeywordWhile:
    return "KeywordWhile";
  case TokenKind::KeywordBreak:
    return "KeywordBreak";
  case TokenKind::KeywordContinue:
    return "KeywordContinue";
  case TokenKind::KeywordGoto:
    return "KeywordGoto";
  case TokenKind::KeywordTry:
    return "KeywordTry";
  case TokenKind::KeywordCatch:
    return "KeywordCatch";
  case TokenKind::KeywordThrow:
    return "KeywordThrow";
  case TokenKind::KeywordTrue:
    return "KeywordTrue";
  case TokenKind::KeywordFalse:
    return "KeywordFalse";
  case TokenKind::KeywordStruct:
    return "KeywordStruct";
  case TokenKind::KeywordTemplate:
    return "KeywordTemplate";
  case TokenKind::KeywordImpl:
    return "KeywordImpl";
  case TokenKind::KeywordOp:
    return "KeywordOp";
  case TokenKind::KeywordAs:
    return "KeywordAs";
  case TokenKind::KeywordSelf:
    return "KeywordSelf";
  case TokenKind::KeywordMut:
    return "KeywordMut";
  case TokenKind::KeywordSet:
    return "KeywordSet";
  case TokenKind::KeywordNone:
    return "KeywordNone";
  case TokenKind::KeywordSizeof:
    return "KeywordSizeof";
  case TokenKind::KeywordSwitch:
    return "KeywordSwitch";
  case TokenKind::KeywordCase:
    return "KeywordCase";
  case TokenKind::KeywordDefault:
    return "KeywordDefault";
  case TokenKind::KeywordDo:
    return "KeywordDo";
  case TokenKind::KeywordTypedef:
    return "KeywordTypedef";
  case TokenKind::KeywordEnum:
    return "KeywordEnum";
  case TokenKind::KeywordUnion:
    return "KeywordUnion";
  case TokenKind::KeywordConst:
    return "KeywordConst";
  case TokenKind::KeywordVolatile:
    return "KeywordVolatile";
  case TokenKind::TypedAssignOperator:
    return "TypedAssignOperator";
  case TokenKind::TypedAdditiveOperator:
    return "TypedAdditiveOperator";
  case TokenKind::TypedMultiplicativeOperator:
    return "TypedMultiplicativeOperator";
  case TokenKind::TypedShiftOperator:
    return "TypedShiftOperator";
  case TokenKind::TypedBitwiseOperator:
    return "TypedBitwiseOperator";
  case TokenKind::TypedPowerOperator:
    return "TypedPowerOperator";
  case TokenKind::Equal:
    return "Equal";
  case TokenKind::Plus:
    return "Plus";
  case TokenKind::Minus:
    return "Minus";
  case TokenKind::Star:
    return "Star";
  case TokenKind::Slash:
    return "Slash";
  case TokenKind::Percent:
    return "Percent";
  case TokenKind::Power:
    return "Power";
  case TokenKind::Less:
    return "Less";
  case TokenKind::Greater:
    return "Greater";
  case TokenKind::LessEqual:
    return "LessEqual";
  case TokenKind::GreaterEqual:
    return "GreaterEqual";
  case TokenKind::EqualEqual:
    return "EqualEqual";
  case TokenKind::BangEqual:
    return "BangEqual";
  case TokenKind::Bang:
    return "Bang";
  case TokenKind::Ampersand:
    return "Ampersand";
  case TokenKind::Pipe:
    return "Pipe";
  case TokenKind::Caret:
    return "Caret";
  case TokenKind::Tilde:
    return "Tilde";
  case TokenKind::AmpersandAmpersand:
    return "AmpersandAmpersand";
  case TokenKind::PipePipe:
    return "PipePipe";
  case TokenKind::ShiftLeft:
    return "ShiftLeft";
  case TokenKind::ShiftRight:
    return "ShiftRight";
  case TokenKind::AmpersandEqual:
    return "AmpersandEqual";
  case TokenKind::PlusPlus:
    return "PlusPlus";
  case TokenKind::MinusMinus:
    return "MinusMinus";
  case TokenKind::Question:
    return "Question";
  case TokenKind::Arrow:
    return "Arrow";
  case TokenKind::Dot:
    return "Dot";
  case TokenKind::Semicolon:
    return "Semicolon";
  case TokenKind::TemplateMark:
    return "TemplateMark";
  case TokenKind::Colon:
    return "Colon";
  case TokenKind::PreprocessorPrefix:
    return "PreprocessorPrefix";
  case TokenKind::LParen:
    return "LParen";
  case TokenKind::RParen:
    return "RParen";
  case TokenKind::LBrace:
    return "LBrace";
  case TokenKind::RBrace:
    return "RBrace";
  case TokenKind::LBracket:
    return "LBracket";
  case TokenKind::RBracket:
    return "RBracket";
  case TokenKind::Comma:
    return "Comma";
  }

  return "Unknown";
}

} // namespace hitsimple::lexer
