#!/usr/bin/env python3
"""Generate deterministic source-level workloads for the Phase 0 benchmarks.

The generated sources exercise the existing HIR pipeline only.  They are not
FlowIR-size claims and are intentionally kept separate from real-project
baseline reports.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


SCHEMA_VERSION = 1
GENERATOR_VERSION = "phase0-source-v1"


@dataclass(frozen=True)
class GenerationConfig:
    short_function_count: int
    medium_function_count: int
    medium_operations_per_function: int
    long_function_count: int
    long_operations_per_function: int
    translation_unit_count: int


PROFILES: dict[str, GenerationConfig] = {
    "smoke": GenerationConfig(
        short_function_count=8,
        medium_function_count=3,
        medium_operations_per_function=8,
        long_function_count=1,
        long_operations_per_function=32,
        translation_unit_count=2,
    ),
    "phase0": GenerationConfig(
        short_function_count=10_000,
        medium_function_count=1_000,
        medium_operations_per_function=64,
        long_function_count=3,
        long_operations_per_function=10_000,
        translation_unit_count=8,
    ),
}


class GenerationError(RuntimeError):
    pass


def parse_positive(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be positive")
    return parsed


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def source_banner(kind: str) -> list[str]:
    return [
        "// Generated by tools/generate_synthetic_workloads.py.",
        f"// Workload: {kind}. Do not edit; regenerate from the manifest.",
        "",
    ]


def function_name(prefix: str, index: int) -> str:
    return f"{prefix}_{index:05d}"


def render_arithmetic_function(name: str, operation_count: int) -> str:
    lines = [f"func {name}(value[4]) -> [4] {{", "    new result[4] = value"]
    for operation_index in range(operation_count):
        increment = operation_index % 17 + 1
        lines.append(f"    result = result + {increment}")
    lines.extend(("    return result", "}", ""))
    return "\n".join(lines)


def render_arithmetic_module(
    kind: str, prefix: str, function_count: int, operation_count: int
) -> str:
    lines = source_banner(kind)
    for index in range(function_count):
        lines.append(
            render_arithmetic_function(function_name(prefix, index), operation_count)
        )
    lines.extend(
        (
            "func main() -> [4] {",
            "    return 0",
            "}",
            "",
        )
    )
    return "\n".join(lines)


def render_control_flow_module() -> str:
    lines = source_banner("wide-shallow, deep-narrow, loop-join, goto, try-catch")
    lines.extend(
        (
            "func wide_shallow(value[4]) -> [4] {",
            "    new result[4] = value",
        )
    )
    for index in range(12):
        lines.extend(
            (
                f"    if (value == {index}) {{",
                f"        result = result + {index + 1}",
                "    } else {",
                "        result = result + 1",
                "    }",
            )
        )
    lines.extend(("    return result", "}", ""))
    lines.extend(
        (
            "func deep_narrow(value[4]) -> [4] {",
            "    new result[4] = value",
        )
    )
    indentation = "    "
    for index in range(10):
        lines.extend(
            (
                f"{indentation}if (result >= 0) {{",
                f"{indentation}    result = result + {index + 1}",
            )
        )
        indentation += "    "
    for _ in range(10):
        indentation = indentation[:-4]
        lines.append(f"{indentation}}}")
    lines.extend(("    return result", "}", ""))
    lines.extend(
        (
            "func loop_and_exception(value[4]) -> [4] {",
            "    new result[4] = value",
            "    new index[4] = 0",
            "    while (index < 16) {",
            "        if (index == 7) {",
            "            result = result + 2",
            "        } else {",
            "            result = result + 1",
            "        }",
            "        index++",
            "    }",
            "    try {",
            "        throw 7",
            "    } catch (error[4]) {",
            "        result = result + error",
            "    }",
            "    goto done",
            "    result = result + 1000",
            "    done: return result",
            "}",
            "",
            "func main() -> [4] {",
            "    return 0",
            "}",
            "",
        )
    )
    return "\n".join(lines)


def render_low_alias_module() -> str:
    return "\n".join(
        source_banner("low-alias")
        + [
            "func low_alias(value[4]) -> [4] {",
            "    new first[4] = value",
            "    new second[4] = first + 1",
            "    return second",
            "}",
            "",
            "func main() -> [4] {",
            "    return 0",
            "}",
            "",
        ]
    )


def render_high_alias_module() -> str:
    return "\n".join(
        source_banner("high-alias")
        + [
            "func high_alias() -> [4] {",
            "    new bytes[4]",
            "    new first[8]",
            "    new second[8]",
            "    first &= &bytes",
            "    second &= &bytes",
            "    [1]*first = 7",
            "    [1]*(second? + 1) = 8",
            "    return 0",
            "}",
            "",
            "func main() -> [4] {",
            "    return high_alias()",
            "}",
            "",
        ]
    )


def render_partial_byte_writes_module() -> str:
    return "\n".join(
        source_banner("partial-byte-writes")
        + [
            "func partial_byte_writes() -> [4] {",
            "    new bytes[4]",
            "    bytes[0] = 20",
            "    bytes[1:2] = 30",
            "    bytes[0]++",
            "    bytes[1:2]--",
            "    return 0",
            "}",
            "",
            "func main() -> [4] {",
            "    return partial_byte_writes()",
            "}",
            "",
        ]
    )


def render_unknown_external_module() -> str:
    return "\n".join(
        source_banner("unknown-external")
        + [
            "extern unknown_external(value[4]) -> [4]",
            "",
            "func call_unknown_external(value[4]) -> [4] {",
            "    return unknown_external(value)",
            "}",
            "",
            "func main() -> [4] {",
            "    return 0",
            "}",
            "",
        ]
    )


def render_checked_failure_module() -> str:
    return "\n".join(
        source_banner("checked-runtime-failure")
        + [
            "$include <stdlib.hsh>",
            "",
            "func main() -> [4] {",
            "    new ptr = alloc(4)",
            "    [1]*(ptr + 4) = 1",
            "    free(ptr)",
            "    return 0",
            "}",
            "",
        ]
    )


def render_multi_tu_library(function_index: int) -> str:
    name = function_name("synthetic_tu", function_index)
    return "\n".join(
        source_banner(f"multi-translation-unit-library-{function_index}")
        + [
            f"func {name}(value[4]) -> [4] {{",
            "    return value + 1",
            "}",
            "",
        ]
    )


def render_multi_tu_main(unit_count: int) -> str:
    lines = source_banner("multi-translation-unit-main")
    for index in range(unit_count):
        lines.append(f"extern {function_name('synthetic_tu', index)}(value[4]) -> [4]")
    lines.extend(("", "func main() -> [4] {", "    new value[4] = 41"))
    for index in range(unit_count):
        lines.append(f"    value = {function_name('synthetic_tu', index)}(value)")
    lines.extend((f"    return value - {41 + unit_count}", "}", ""))
    return "\n".join(lines)


def render_incremental_library(delta: int) -> str:
    return "\n".join(
        source_banner(f"incremental-library-delta-{delta}")
        + [
            "func incremental_value(value[4]) -> [4] {",
            f"    return value + {delta}",
            "}",
            "",
        ]
    )


def render_incremental_main() -> str:
    return "\n".join(
        source_banner("incremental-main")
        + [
            "extern incremental_value(value[4]) -> [4]",
            "",
            "func main() -> [4] {",
            "    return incremental_value(41) - 42",
            "}",
            "",
        ]
    )


def write_source(root: Path, relative_path: str, text: str) -> None:
    path = root / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def source_file_metadata(root: Path) -> list[dict[str, int | str]]:
    files: list[dict[str, int | str]] = []
    for path in sorted(root.rglob("*.hs")):
        files.append(
            {
                "path": path.relative_to(root).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256_file(path),
            }
        )
    return files


def compiler_workload(
    identifier: str,
    description: str,
    source_paths: Iterable[str],
    coverage: Iterable[str],
    compiler_options: Iterable[str] = (),
    execution_expectation: str = "success",
) -> dict[str, object]:
    return {
        "id": identifier,
        "description": description,
        "source_paths": list(source_paths),
        "compiler_options": list(compiler_options),
        "coverage": list(coverage),
        "execution_expectation": execution_expectation,
    }


def generate(root: Path, profile: str, config: GenerationConfig) -> dict[str, object]:
    write_source(
        root,
        "scalar/short_functions.hs",
        render_arithmetic_module(
            "short-functions",
            "short_function",
            config.short_function_count,
            1,
        ),
    )
    write_source(
        root,
        "scalar/medium_functions.hs",
        render_arithmetic_module(
            "medium-functions",
            "medium_function",
            config.medium_function_count,
            config.medium_operations_per_function,
        ),
    )
    write_source(
        root,
        "scalar/long_functions.hs",
        render_arithmetic_module(
            "long-functions",
            "long_function",
            config.long_function_count,
            config.long_operations_per_function,
        ),
    )
    write_source(root, "shapes/control_flow.hs", render_control_flow_module())
    write_source(root, "shapes/low_alias.hs", render_low_alias_module())
    write_source(root, "shapes/high_alias.hs", render_high_alias_module())
    write_source(
        root, "shapes/partial_byte_writes.hs", render_partial_byte_writes_module()
    )
    write_source(
        root, "shapes/unknown_external.hs", render_unknown_external_module()
    )
    write_source(root, "checked_failure/oob.hs", render_checked_failure_module())

    multi_tu_sources: list[str] = []
    for index in range(config.translation_unit_count):
        relative_path = f"multi_tu/library_{index:03d}.hs"
        write_source(root, relative_path, render_multi_tu_library(index))
        multi_tu_sources.append(relative_path)
    multi_tu_sources.append("multi_tu/main.hs")
    write_source(root, "multi_tu/main.hs", render_multi_tu_main(config.translation_unit_count))

    write_source(
        root, "incremental/base/library.hs", render_incremental_library(1)
    )
    write_source(root, "incremental/base/main.hs", render_incremental_main())
    write_source(
        root, "incremental/changed/library.hs", render_incremental_library(2)
    )
    write_source(root, "incremental/changed/main.hs", render_incremental_main())

    workloads = [
        compiler_workload(
            "short_functions",
            "Many short, straight-line functions.",
            ("scalar/short_functions.hs",),
            ("short_functions",),
        ),
        compiler_workload(
            "medium_functions",
            "Medium functions with a fixed number of source statements.",
            ("scalar/medium_functions.hs",),
            ("medium_functions",),
        ),
        compiler_workload(
            "long_functions",
            "A small set of long, straight-line functions.",
            ("scalar/long_functions.hs",),
            ("long_functions",),
        ),
        compiler_workload(
            "control_flow_shapes",
            "Wide and deep control flow, loops, joins, goto, and exceptions.",
            ("shapes/control_flow.hs",),
            ("wide_shallow_cfg", "deep_narrow_cfg", "loops", "joins", "goto", "try_catch_throw"),
        ),
        compiler_workload(
            "low_alias",
            "Independent scalar local storage.",
            ("shapes/low_alias.hs",),
            ("low_alias",),
        ),
        compiler_workload(
            "high_alias",
            "Two address bindings to the same byte storage.",
            ("shapes/high_alias.hs",),
            ("high_alias",),
        ),
        compiler_workload(
            "partial_byte_writes",
            "Overlapping byte and byte-slice writes.",
            ("shapes/partial_byte_writes.hs",),
            ("partial_byte_writes",),
        ),
        compiler_workload(
            "unknown_external",
            "An unresolved extern call for conservative external-effect analysis.",
            ("shapes/unknown_external.hs",),
            ("unknown_external",),
            ("--emit-llvm",),
            "emit_llvm_only",
        ),
        compiler_workload(
            "checked_oob_failure",
            "A checked-mode out-of-bounds write expected to fail at runtime.",
            ("checked_failure/oob.hs",),
            ("checked_failure",),
            ("--checked",),
            "runtime_failure",
        ),
        compiler_workload(
            "multi_translation_unit",
            "Separate library and main translation units.",
            multi_tu_sources,
            ("multiple_translation_units",),
        ),
        compiler_workload(
            "incremental_base",
            "Base version of a two-translation-unit incremental workload.",
            ("incremental/base/library.hs", "incremental/base/main.hs"),
            ("incremental", "multiple_translation_units"),
        ),
        compiler_workload(
            "incremental_changed",
            "Changed version with exactly one modified library source file.",
            ("incremental/changed/library.hs", "incremental/changed/main.hs"),
            ("incremental", "multiple_translation_units"),
        ),
    ]
    return {
        "schema_version": SCHEMA_VERSION,
        "kind": "hitsimple_synthetic_source_workloads",
        "generator": {
            "version": GENERATOR_VERSION,
            "determinism": "output is a pure function of profile and configuration; no clock or random input is used",
        },
        "profile": profile,
        "configuration": asdict(config),
        "scope": {
            "pipeline": "current source to HIR to LLVM path",
            "excluded": [
                "FlowIR instruction-count workloads",
                "GPU cold, warm, resident, or incremental measurements",
                "CPU multi-threaded analysis conclusions",
            ],
            "reporting_rule": "synthetic results are controlled-variable measurements and do not establish real-project compiler performance",
        },
        "incremental_change": {
            "base_root": "incremental/base",
            "changed_root": "incremental/changed",
            "changed_paths": ["library.hs"],
            "unchanged_paths": ["main.hs"],
        },
        "workloads": workloads,
        "files": source_file_metadata(root),
    }


def write_manifest(root: Path, manifest: dict[str, object]) -> None:
    path = root / "manifest.json"
    with path.open("w", encoding="utf-8", newline="\n") as output:
        json.dump(manifest, output, indent=2, sort_keys=True, ensure_ascii=True)
        output.write("\n")


def resolve_config(arguments: argparse.Namespace) -> GenerationConfig:
    profile_config = PROFILES[arguments.profile]
    values = asdict(profile_config)
    for argument_name, field_name in (
        ("short_functions", "short_function_count"),
        ("medium_functions", "medium_function_count"),
        ("medium_operations", "medium_operations_per_function"),
        ("long_functions", "long_function_count"),
        ("long_operations", "long_operations_per_function"),
        ("translation_units", "translation_unit_count"),
    ):
        value = getattr(arguments, argument_name)
        if value is not None:
            values[field_name] = value
    return GenerationConfig(**values)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic Phase 0 source-level synthetic workloads."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="destination directory; it must not exist or be empty unless --force is set",
    )
    parser.add_argument(
        "--profile",
        choices=sorted(PROFILES),
        default="phase0",
        help="generation scale (default: phase0)",
    )
    parser.add_argument(
        "--list-profiles",
        action="store_true",
        help="print profile names and configurations, then exit",
    )
    parser.add_argument("--short-functions", type=parse_positive)
    parser.add_argument("--medium-functions", type=parse_positive)
    parser.add_argument("--medium-operations", type=parse_positive)
    parser.add_argument("--long-functions", type=parse_positive)
    parser.add_argument("--long-operations", type=parse_positive)
    parser.add_argument("--translation-units", type=parse_positive)
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing non-empty output directory",
    )
    return parser.parse_args()


def prepare_destination(output_dir: Path, force: bool) -> None:
    if output_dir.exists():
        if not output_dir.is_dir():
            raise GenerationError(f"output path is not a directory: {output_dir}")
        if any(output_dir.iterdir()):
            if not force:
                raise GenerationError(
                    f"output directory is not empty: {output_dir}; pass --force to replace it"
                )
            shutil.rmtree(output_dir)
        else:
            output_dir.rmdir()
    output_dir.parent.mkdir(parents=True, exist_ok=True)


def main() -> int:
    arguments = parse_arguments()
    if arguments.list_profiles:
        for name in sorted(PROFILES):
            print(f"{name}: {json.dumps(asdict(PROFILES[name]), sort_keys=True)}")
        return 0
    if arguments.output_dir is None:
        raise GenerationError("--output-dir is required unless --list-profiles is used")

    output_dir = arguments.output_dir.resolve()
    config = resolve_config(arguments)
    prepare_destination(output_dir, arguments.force)
    staging_dir = Path(
        tempfile.mkdtemp(prefix=f".{output_dir.name}.", dir=output_dir.parent)
    )
    try:
        manifest = generate(staging_dir, arguments.profile, config)
        write_manifest(staging_dir, manifest)
        staging_dir.replace(output_dir)
    except Exception:
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise
    print(output_dir / "manifest.json")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:
        print(f"synthetic workload generator: error: {error}", file=sys.stderr)
        raise SystemExit(1)
