if(NOT DEFINED JSON)
  message(FATAL_ERROR "JSON is required")
endif()
if(NOT DEFINED EXPECTED_OUTCOME)
  message(FATAL_ERROR "EXPECTED_OUTCOME is required")
endif()
if(NOT EXISTS "${JSON}")
  message(FATAL_ERROR "timing JSON does not exist: ${JSON}")
endif()

file(READ "${JSON}" timing_json)
string(JSON schema_version GET "${timing_json}" schema_version)
if(NOT schema_version EQUAL 1)
  message(FATAL_ERROR "unexpected timing schema version: ${schema_version}")
endif()
string(JSON outcome GET "${timing_json}" outcome)
if(NOT outcome STREQUAL EXPECTED_OUTCOME)
  message(FATAL_ERROR "expected outcome ${EXPECTED_OUTCOME}, got ${outcome}")
endif()

if(DEFINED EXPECTED_FAILED_STAGE)
  string(JSON failed_stage GET "${timing_json}" failed_stage)
  if(NOT failed_stage STREQUAL EXPECTED_FAILED_STAGE)
    message(FATAL_ERROR "expected failed stage ${EXPECTED_FAILED_STAGE}, got ${failed_stage}")
  endif()
endif()

if(DEFINED EXPECTED_TU_COUNT)
  string(JSON translation_unit_count GET "${timing_json}" translation_unit_count)
  if(NOT translation_unit_count EQUAL EXPECTED_TU_COUNT)
    message(FATAL_ERROR "expected ${EXPECTED_TU_COUNT} translation units, got ${translation_unit_count}")
  endif()
endif()

if(DEFINED EXPECTED_C_COMPAT_LOWERING_STATUS)
  string(JSON c_compat_lowering_status GET "${timing_json}" translation_units 0 stages c_compat_lowering status)
  if(NOT c_compat_lowering_status STREQUAL EXPECTED_C_COMPAT_LOWERING_STATUS)
    message(FATAL_ERROR "expected c_compat_lowering status ${EXPECTED_C_COMPAT_LOWERING_STATUS}, got ${c_compat_lowering_status}")
  endif()
endif()
